spring:
  application:
    name: api-gateway

  cloud:
    config:
      uri: http://localhost:8888

#zuul:
#  routes:
#    address-service:
#      path: /address/**
#      serviceId: address-service
